// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型编号。客户端与服务器共用,作为协议帧里的 [类型] 字段。
type MsgId int32

const (
	MsgId_MSG_UNKNOWN        MsgId = 0
	MsgId_MSG_LOGIN_REQ      MsgId = 1
	MsgId_MSG_LOGIN_RESP     MsgId = 2
	MsgId_MSG_MOVE_REQ       MsgId = 3
	MsgId_MSG_MOVE_BROADCAST MsgId = 4
	MsgId_MSG_PLAYER_ENTER   MsgId = 5 // 有玩家进入我的视野
	MsgId_MSG_PLAYER_LEAVE   MsgId = 6 // 有玩家离开我的视野
	MsgId_MSG_STATE_SYNC     MsgId = 7 // AOI 状态同步快照
	MsgId_MSG_SPECTATE       MsgId = 8 // 客户端请求以"上帝视角"观战(收全量状态)
	MsgId_MSG_MINIMAP_SYNC   MsgId = 9 // 低频全场快照,给玩家画小地图(复用 StateSync 结构)
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0: "MSG_UNKNOWN",
		1: "MSG_LOGIN_REQ",
		2: "MSG_LOGIN_RESP",
		3: "MSG_MOVE_REQ",
		4: "MSG_MOVE_BROADCAST",
		5: "MSG_PLAYER_ENTER",
		6: "MSG_PLAYER_LEAVE",
		7: "MSG_STATE_SYNC",
		8: "MSG_SPECTATE",
		9: "MSG_MINIMAP_SYNC",
	}
	MsgId_value = map[string]int32{
		"MSG_UNKNOWN":        0,
		"MSG_LOGIN_REQ":      1,
		"MSG_LOGIN_RESP":     2,
		"MSG_MOVE_REQ":       3,
		"MSG_MOVE_BROADCAST": 4,
		"MSG_PLAYER_ENTER":   5,
		"MSG_PLAYER_LEAVE":   6,
		"MSG_STATE_SYNC":     7,
		"MSG_SPECTATE":       8,
		"MSG_MINIMAP_SYNC":   9,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

// 登录请求:阶段 1 做"最小登录",只带一个用户名,不校验密码。
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// 登录响应:服务器分配一个玩家 ID 返回。
type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 失败原因 / 欢迎语
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LoginResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 移动请求:客户端上报自己想移动到的坐标。
type MoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveReq) Reset() {
	*x = MoveReq{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReq) ProtoMessage() {}

func (x *MoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReq.ProtoReflect.Descriptor instead.
func (*MoveReq) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *MoveReq) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveReq) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 移动广播:把某个玩家的新坐标推给视野内的其他玩家。
type MoveBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveBroadcast) Reset() {
	*x = MoveBroadcast{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveBroadcast) ProtoMessage() {}

func (x *MoveBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveBroadcast.ProtoReflect.Descriptor instead.
func (*MoveBroadcast) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *MoveBroadcast) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MoveBroadcast) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveBroadcast) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 进入视野:有一个玩家出现在了我的视野里,带上它的位置以便客户端生成它。
type PlayerEnter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnter) Reset() {
	*x = PlayerEnter{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnter) ProtoMessage() {}

func (x *PlayerEnter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnter.ProtoReflect.Descriptor instead.
func (*PlayerEnter) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerEnter) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerEnter) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerEnter) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 离开视野:有一个玩家离开了我的视野,客户端据此把它移除。
type PlayerLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	mi := &file_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerLeave) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 状态快照里的单个玩家状态。
type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerState) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 状态同步:把观察者视野内其他玩家的位置打包成一份快照,10Hz 广播。
type StateSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerState         `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSync) Reset() {
	*x = StateSync{}
	mi := &file_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSync) ProtoMessage() {}

func (x *StateSync) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSync.ProtoReflect.Descriptor instead.
func (*StateSync) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *StateSync) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x04game\"&\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\\\n" +
	"\tLoginResp\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"%\n" +
	"\aMoveReq\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"H\n" +
	"\rMoveBroadcast\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"F\n" +
	"\vPlayerEnter\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"*\n" +
	"\vPlayerLeave\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"F\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"8\n" +
	"\tStateSync\x12+\n" +
	"\aplayers\x18\x01 \x03(\v2\x11.game.PlayerStateR\aplayers*\xd1\x01\n" +
	"\x05MsgId\x12\x0f\n" +
	"\vMSG_UNKNOWN\x10\x00\x12\x11\n" +
	"\rMSG_LOGIN_REQ\x10\x01\x12\x12\n" +
	"\x0eMSG_LOGIN_RESP\x10\x02\x12\x10\n" +
	"\fMSG_MOVE_REQ\x10\x03\x12\x16\n" +
	"\x12MSG_MOVE_BROADCAST\x10\x04\x12\x14\n" +
	"\x10MSG_PLAYER_ENTER\x10\x05\x12\x14\n" +
	"\x10MSG_PLAYER_LEAVE\x10\x06\x12\x12\n" +
	"\x0eMSG_STATE_SYNC\x10\a\x12\x10\n" +
	"\fMSG_SPECTATE\x10\b\x12\x14\n" +
	"\x10MSG_MINIMAP_SYNC\x10\tB0Z.github.com/xingguanglang/MMOServer-Demo/pkg/pbb\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_game_proto_goTypes = []any{
	(MsgId)(0),            // 0: game.MsgId
	(*LoginReq)(nil),      // 1: game.LoginReq
	(*LoginResp)(nil),     // 2: game.LoginResp
	(*MoveReq)(nil),       // 3: game.MoveReq
	(*MoveBroadcast)(nil), // 4: game.MoveBroadcast
	(*PlayerEnter)(nil),   // 5: game.PlayerEnter
	(*PlayerLeave)(nil),   // 6: game.PlayerLeave
	(*PlayerState)(nil),   // 7: game.PlayerState
	(*StateSync)(nil),     // 8: game.StateSync
}
var file_proto_game_proto_depIdxs = []int32{
	7, // 0: game.StateSync.players:type_name -> game.PlayerState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		EnumInfos:         file_proto_game_proto_enumTypes,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
