// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: proto/scene.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SceneService_Session_FullMethodName = "/game.SceneService/Session"
)

// SceneServiceClient is the client API for SceneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SceneService 是网关与场景服之间的跨进程接口。
// 用一条双向流承载:上行(网关→场景)玩家事件,下行(场景→网关)要发给玩家的消息。
type SceneServiceClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayEvent, SceneEvent], error)
}

type sceneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSceneServiceClient(cc grpc.ClientConnInterface) SceneServiceClient {
	return &sceneServiceClient{cc}
}

func (c *sceneServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayEvent, SceneEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SceneService_ServiceDesc.Streams[0], SceneService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GatewayEvent, SceneEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SceneService_SessionClient = grpc.BidiStreamingClient[GatewayEvent, SceneEvent]

// SceneServiceServer is the server API for SceneService service.
// All implementations must embed UnimplementedSceneServiceServer
// for forward compatibility.
//
// SceneService 是网关与场景服之间的跨进程接口。
// 用一条双向流承载:上行(网关→场景)玩家事件,下行(场景→网关)要发给玩家的消息。
type SceneServiceServer interface {
	Session(grpc.BidiStreamingServer[GatewayEvent, SceneEvent]) error
	mustEmbedUnimplementedSceneServiceServer()
}

// UnimplementedSceneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSceneServiceServer struct{}

func (UnimplementedSceneServiceServer) Session(grpc.BidiStreamingServer[GatewayEvent, SceneEvent]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedSceneServiceServer) mustEmbedUnimplementedSceneServiceServer() {}
func (UnimplementedSceneServiceServer) testEmbeddedByValue()                      {}

// UnsafeSceneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SceneServiceServer will
// result in compilation errors.
type UnsafeSceneServiceServer interface {
	mustEmbedUnimplementedSceneServiceServer()
}

func RegisterSceneServiceServer(s grpc.ServiceRegistrar, srv SceneServiceServer) {
	// If the following call panics, it indicates UnimplementedSceneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SceneService_ServiceDesc, srv)
}

func _SceneService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SceneServiceServer).Session(&grpc.GenericServerStream[GatewayEvent, SceneEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SceneService_SessionServer = grpc.BidiStreamingServer[GatewayEvent, SceneEvent]

// SceneService_ServiceDesc is the grpc.ServiceDesc for SceneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SceneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.SceneService",
	HandlerType: (*SceneServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _SceneService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/scene.proto",
}
