// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/scene.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家进入场景。
type PlayerJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	mi := &file_proto_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerJoin) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerJoin) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerJoin) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 玩家移动。
type PlayerMoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMoveReq) Reset() {
	*x = PlayerMoveReq{}
	mi := &file_proto_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMoveReq) ProtoMessage() {}

func (x *PlayerMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMoveReq.ProtoReflect.Descriptor instead.
func (*PlayerMoveReq) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerMoveReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerMoveReq) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMoveReq) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 玩家离开场景。
type PlayerLeaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeaveReq) Reset() {
	*x = PlayerLeaveReq{}
	mi := &file_proto_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeaveReq) ProtoMessage() {}

func (x *PlayerLeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeaveReq.ProtoReflect.Descriptor instead.
func (*PlayerLeaveReq) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerLeaveReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// GatewayEvent 是网关上行给场景的事件(一次一种)。
type GatewayEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*GatewayEvent_Join
	//	*GatewayEvent_Move
	//	*GatewayEvent_Leave
	Event         isGatewayEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayEvent) Reset() {
	*x = GatewayEvent{}
	mi := &file_proto_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayEvent) ProtoMessage() {}

func (x *GatewayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayEvent.ProtoReflect.Descriptor instead.
func (*GatewayEvent) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayEvent) GetEvent() isGatewayEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GatewayEvent) GetJoin() *PlayerJoin {
	if x != nil {
		if x, ok := x.Event.(*GatewayEvent_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *GatewayEvent) GetMove() *PlayerMoveReq {
	if x != nil {
		if x, ok := x.Event.(*GatewayEvent_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *GatewayEvent) GetLeave() *PlayerLeaveReq {
	if x != nil {
		if x, ok := x.Event.(*GatewayEvent_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

type isGatewayEvent_Event interface {
	isGatewayEvent_Event()
}

type GatewayEvent_Join struct {
	Join *PlayerJoin `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type GatewayEvent_Move struct {
	Move *PlayerMoveReq `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

type GatewayEvent_Leave struct {
	Leave *PlayerLeaveReq `protobuf:"bytes,3,opt,name=leave,proto3,oneof"`
}

func (*GatewayEvent_Join) isGatewayEvent_Event() {}

func (*GatewayEvent_Move) isGatewayEvent_Event() {}

func (*GatewayEvent_Leave) isGatewayEvent_Event() {}

// SceneEvent 是场景下行给网关的事件:把已编码好的消息(payload)发给 target_player_id。
// 网关据此把 payload 套上协议帧、写给对应玩家的连接。
type SceneEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetPlayerId int64                  `protobuf:"varint,1,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	MsgType        uint32                 `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"` // 复用 MsgId(StateSync / PlayerEnter / PlayerLeave)
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                 // 已序列化的 protobuf 消息体
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SceneEvent) Reset() {
	*x = SceneEvent{}
	mi := &file_proto_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneEvent) ProtoMessage() {}

func (x *SceneEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneEvent.ProtoReflect.Descriptor instead.
func (*SceneEvent) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{4}
}

func (x *SceneEvent) GetTargetPlayerId() int64 {
	if x != nil {
		return x.TargetPlayerId
	}
	return 0
}

func (x *SceneEvent) GetMsgType() uint32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SceneEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_scene_proto protoreflect.FileDescriptor

const file_proto_scene_proto_rawDesc = "" +
	"\n" +
	"\x11proto/scene.proto\x12\x04game\"E\n" +
	"\n" +
	"PlayerJoin\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"H\n" +
	"\rPlayerMoveReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"-\n" +
	"\x0ePlayerLeaveReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\x98\x01\n" +
	"\fGatewayEvent\x12&\n" +
	"\x04join\x18\x01 \x01(\v2\x10.game.PlayerJoinH\x00R\x04join\x12)\n" +
	"\x04move\x18\x02 \x01(\v2\x13.game.PlayerMoveReqH\x00R\x04move\x12,\n" +
	"\x05leave\x18\x03 \x01(\v2\x14.game.PlayerLeaveReqH\x00R\x05leaveB\a\n" +
	"\x05event\"k\n" +
	"\n" +
	"SceneEvent\x12(\n" +
	"\x10target_player_id\x18\x01 \x01(\x03R\x0etargetPlayerId\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\rR\amsgType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload2C\n" +
	"\fSceneService\x123\n" +
	"\aSession\x12\x12.game.GatewayEvent\x1a\x10.game.SceneEvent(\x010\x01B0Z.github.com/xingguanglang/MMOServer-Demo/pkg/pbb\x06proto3"

var (
	file_proto_scene_proto_rawDescOnce sync.Once
	file_proto_scene_proto_rawDescData []byte
)

func file_proto_scene_proto_rawDescGZIP() []byte {
	file_proto_scene_proto_rawDescOnce.Do(func() {
		file_proto_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scene_proto_rawDesc), len(file_proto_scene_proto_rawDesc)))
	})
	return file_proto_scene_proto_rawDescData
}

var file_proto_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_scene_proto_goTypes = []any{
	(*PlayerJoin)(nil),     // 0: game.PlayerJoin
	(*PlayerMoveReq)(nil),  // 1: game.PlayerMoveReq
	(*PlayerLeaveReq)(nil), // 2: game.PlayerLeaveReq
	(*GatewayEvent)(nil),   // 3: game.GatewayEvent
	(*SceneEvent)(nil),     // 4: game.SceneEvent
}
var file_proto_scene_proto_depIdxs = []int32{
	0, // 0: game.GatewayEvent.join:type_name -> game.PlayerJoin
	1, // 1: game.GatewayEvent.move:type_name -> game.PlayerMoveReq
	2, // 2: game.GatewayEvent.leave:type_name -> game.PlayerLeaveReq
	3, // 3: game.SceneService.Session:input_type -> game.GatewayEvent
	4, // 4: game.SceneService.Session:output_type -> game.SceneEvent
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_scene_proto_init() }
func file_proto_scene_proto_init() {
	if File_proto_scene_proto != nil {
		return
	}
	file_proto_scene_proto_msgTypes[3].OneofWrappers = []any{
		(*GatewayEvent_Join)(nil),
		(*GatewayEvent_Move)(nil),
		(*GatewayEvent_Leave)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scene_proto_rawDesc), len(file_proto_scene_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scene_proto_goTypes,
		DependencyIndexes: file_proto_scene_proto_depIdxs,
		MessageInfos:      file_proto_scene_proto_msgTypes,
	}.Build()
	File_proto_scene_proto = out.File
	file_proto_scene_proto_goTypes = nil
	file_proto_scene_proto_depIdxs = nil
}
